export const ADD_REVIEW_REQUSET = "ADD_REVIEW_REQUSET";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";
