export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_LOGOUT = "USER_REGISTER_LOGOUT";

export const USER_PROFILE_REVIEWS_REQUEST = "USER_PROFILE_REVIEWS_REQUEST";
export const USER_PROFILE_REVIEWS_SUCCESS = "USER_PROFILE_REVIEWS_SUCCESS";
export const USER_PROFILE_REVIEWS_FAIL = "USER_PROFILE_REVIEWS_FAIL";
export const USER_PROFILE_REVIEWS_RESET = "USER_PROFILE_REVIEWS_RESET";

export const USER_PROFILE_ORDERS_REQUEST = "USER_PROFILE_ORDERS_REQUEST";
export const USER_PROFILE_ORDERS_SUCCESS = "USER_PROFILE_ORDERS_SUCCESS";
export const USER_PROFILE_ORDERS_FAIL = "USER_PROFILE_ORDERS_FAIL";
export const USER_PROFILE_ORDERS_RESET = "USER_PROFILE_ORDERS_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";
